"""
Extract the React-in-HTML tools into real frontend modules.

The Scenario Planner and Budget Playground were authored as JSX compiled
in the browser by CDN Babel; the Investment Optimizer is vanilla JS.
This script lifts each into frontend/src so Vite precompiles them into
the application bundle:

  scenario_planner.html   -> src/tools/ScenarioPlannerApp.jsx + .css
  budget_playground.html  -> src/tools/BudgetPlaygroundApp.jsx + .css
  investment_optimizer    -> src/tools/investmentOptimizer.js + .css

Transformations are deliberately minimal and mechanical - the tool code
itself is unchanged apart from environment seams (API base URLs, module
exports, the retired local-storage shim).

Re-run after editing the source HTML files; the extracted files are
generated artifacts and marked as such.
"""

import re

HEADER = "// GENERATED by scripts/extract_frontend_tools.py - edit the source HTML, then re-run.\n"


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write(path, content):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {path} ({len(content.splitlines())} lines)")


def extract_style(html):
    styles = re.findall(r"<style[^>]*>([\s\S]*?)</style>", html)
    return "\n".join(styles)


def extract_babel(html):
    m = re.search(r'<script type="text/babel"[^>]*>([\s\S]*?)</script>', html)
    if not m:
        raise SystemExit("no babel script found")
    return m.group(1)


def strip_mount(js):
    """Remove the browser mount call; the app component gets exported."""
    js = re.sub(
        r"ReactDOM\.createRoot\([^)]*\)\.render\([\s\S]*?\);?\s*$", "", js.strip())
    js = re.sub(r"ReactDOM\.render\([\s\S]*?\);?\s*$", "", js.strip())
    # Two-statement variant: const root = ReactDOM.createRoot(...); root.render(...)
    js = re.sub(
        r"(?:const|let|var)\s+\w+\s*=\s*ReactDOM\.createRoot\([\s\S]*?\);\s*"
        r"\w+\.render\([\s\S]*?\);?\s*$", "", js.strip())
    js = js.strip()
    if "ReactDOM" in js:
        raise SystemExit("unremoved ReactDOM mount remains in extracted tool")
    return js


def scenario_planner():
    html = read("modules/scenario_planner_html/scenario_planner.html")
    js = strip_mount(extract_babel(html))
    js = HEADER + (
        "import React from 'react';\n"
        "import './ScenarioPlannerApp.css';\n"
        "const Chart = window.Chart;\n\n"
    ) + js + "\n\nexport default App;\n"
    write("frontend/src/tools/ScenarioPlannerApp.jsx", js)
    write("frontend/src/tools/ScenarioPlannerApp.css",
          "/* GENERATED from scenario_planner.html styles */\n" + extract_style(html))


def budget_playground():
    html = read("modules/navi/budget_playground.html")
    js = strip_mount(extract_babel(html))

    # Environment seams: unified same-origin API instead of the Node port
    # and the static-hosting shim
    js = js.replace(
        "const API = (typeof window !== 'undefined' && window.BUDGET_PLAYGROUND_API_URL) || 'http://localhost:5002';",
        "const API = '';  // unified platform API, same origin")
    js = js.replace("const BASE = API + '/api';",
                    "const BASE = '/api/bp';")
    js = js.replace(
        "const req = (url, opts={}) => window.gsBpRequest(url, opts);",
        "const req = (url, opts={}) => fetch(url, { credentials: 'same-origin', "
        "...opts, headers: { 'Content-Type': 'application/json', ...(opts.headers||{}) } })"
        ".then(r => r.ok ? r.json() : r.json().then(e => { "
        "throw new Error(e.detail || e.error || 'Request failed'); }));")
    js = js.replace("window.gsBpExportCsv(BASE, activeId);",
                    "window.open(BASE + '/scenarios/' + activeId + '/export.csv', '_blank');")

    js = HEADER + (
        "import React from 'react';\n"
        "import './BudgetPlaygroundApp.css';\n"
        "const Chart = window.Chart;\n\n"
    ) + js + "\n\nexport default App;\n"
    write("frontend/src/tools/BudgetPlaygroundApp.jsx", js)
    write("frontend/src/tools/BudgetPlaygroundApp.css",
          "/* GENERATED from budget_playground.html styles */\n" + extract_style(html))


def investment_optimizer():
    html = read("modules/navi/investment_optimizer_html.html")
    body_m = re.search(r"<body[^>]*>([\s\S]*?)<script>", html)
    if not body_m:
        raise SystemExit("optimizer body not found")
    body = body_m.group(1).strip()
    script_m = re.search(r"<script>([\s\S]*)</script>\s*</body>", html)
    if not script_m:
        raise SystemExit("optimizer script not found")
    script = script_m.group(1)

    # The DOMContentLoaded hook never fires when mounted dynamically;
    # convert it into an exported init
    hook = "window.addEventListener('DOMContentLoaded', function() {"
    if hook not in script:
        raise SystemExit("optimizer init hook not found")
    script = script.replace(hook, "function __optimizerInit() {")
    # Close of that listener is the file's final `});`
    idx = script.rstrip().rfind("});")
    script = script.rstrip()[:idx] + "}\n"

    # Inline onclick="fn(...)" handlers resolve at global scope; the
    # bundle's module scope hides these functions, so re-export every
    # handler that is actually defined in the script onto window.
    handler_names = sorted(set(re.findall(r'onclick="(\w+)\(', body)
                               + re.findall(r'onclick="(\w+)\(', script)))
    defined = [n for n in handler_names
               if re.search(r"\bfunction\s+" + n + r"\b", script)]
    missing = set(handler_names) - set(defined)
    if missing:
        raise SystemExit(f"optimizer onclick handlers not defined: {missing}")
    globals_line = ("Object.assign(window, { " + ", ".join(defined) + " });\n"
                    if defined else "")

    module = HEADER + (
        "import './investmentOptimizer.css';\n\n"
        "const BODY_HTML = " + repr(body) + ";\n\n"
        + script + "\n"
        + globals_line +
        "\nexport function mountInvestmentOptimizer(el) {\n"
        "  el.innerHTML = BODY_HTML;\n"
        "  __optimizerInit();\n"
        "}\n")
    write("frontend/src/tools/investmentOptimizer.js", module)
    write("frontend/src/tools/investmentOptimizer.css",
          "/* GENERATED from investment_optimizer_html.html styles */\n" + extract_style(html))


def vendor_views():
    for name in ("demo_views.js", "bi_sandbox.js"):
        src = read(f"public/assets/{name}")
        if name == "demo_views.js":
            # Allow the SPA to inject the live bundle instead of fetching
            # the demo JSON
            src = src.replace(
                "  window.DEMO_VIEWS = {\n    load: loadData,",
                "  window.DEMO_VIEWS = {\n    load: loadData,\n"
                "    setData: function (d) { MASTER = d; DATA = personaView(d); "
                "loadPromise = Promise.resolve(DATA); },")
            assert "setData" in src
        write(f"frontend/src/vendor/{name}",
              "// GENERATED copy for the SPA bundle - source of truth is public/assets/.\n" + src)


if __name__ == "__main__":
    scenario_planner()
    budget_playground()
    investment_optimizer()
    vendor_views()
